// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFnYHd3tuwQNeERQFngFbckHZHami80-g',
    appId: '1:156273234728:web:b01dc54e620872363f361d',
    messagingSenderId: '156273234728',
    projectId: 'chat-app-6665a',
    authDomain: 'chat-app-6665a.firebaseapp.com',
    storageBucket: 'chat-app-6665a.appspot.com',
    measurementId: 'G-KLRG5EY43R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBek09DewQfxojvcoXE5Am48Oi-nx4Qy-s',
    appId: '1:156273234728:android:05533d44ca3ff6523f361d',
    messagingSenderId: '156273234728',
    projectId: 'chat-app-6665a',
    storageBucket: 'chat-app-6665a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjyEPASZZnBcVSoqZ1VQegi52oYW3hv4',
    appId: '1:156273234728:ios:415a6ea8d108e6cf3f361d',
    messagingSenderId: '156273234728',
    projectId: 'chat-app-6665a',
    storageBucket: 'chat-app-6665a.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjyEPASZZnBcVSoqZ1VQegi52oYW3hv4',
    appId: '1:156273234728:ios:c3d4da5f8d4587543f361d',
    messagingSenderId: '156273234728',
    projectId: 'chat-app-6665a',
    storageBucket: 'chat-app-6665a.appspot.com',
    iosBundleId: 'com.example.fire.RunnerTests',
  );
}
